const StatusAula = Object.freeze({
    SOLICITADA: 'SOLICITADA',
    CONFIRMADA: 'CONFIRMADA',
    CANCELADA_PELO_ALUNO: 'CANCELADA_PELO_ALUNO',
    CANCELADA_PELO_PROFESSOR: 'CANCELADA_PELO_PROFESSOR',
    REALIZADA: 'REALIZADA'
});

module.exports = StatusAula;
